config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

    resources :students

end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@students = Student.all
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def show
		@student = Student.find params[:id]
	end	

	def new
		@student = Student.new
	end

	def create
		@student = Student.create que_params
		redirect_to root_path
	end	

	def edit
		@student = Student.find params[:id]
	end	

	def update
		@student = Student.find params[:id]
		@student.update_attributes que_params
		redirect_to root_path
	end
		
	def destroy
		@student = Student.find params[:id]
		@student.delete
		redirect_to root_path
	end	
private
	def que_params
		params.require(:student).permit(:name)
	end		
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/index.html.erb
<h1>Yay bey</h1>

<%= link_to "New Student", new_student_path %>
<br>
<% @students.each do |student| %>
	<%= link_to student.name, student_path(student) %>
	<%= link_to "Edit", edit_student_path(student) %>
	<%= link_to "Delete", student_path(student), method: :delete %>
	<br>
<% end %>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Day11</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= form_for @student do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.submit %>
<% end %>	

app/views/students/new.html.erb
<h1>New Student</h1>

<%= form_for @student do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.submit %>
<% end %>	

app/views/students/show.html.erb
<h1>Show Data</h1>

<%= @student.name %>

<%= link_to "Home", root_path %>